INFO:root:Informational message.
ERROR:root:An error has occurred!
ERROR:ex:Error!
Traceback (most recent call last):
  File "C:/Projects/put_a_config_on_it/logger.py", line 9, in <module>
    raise RuntimeError
RuntimeError
INFO:root:Informational message.
ERROR:root:An error has occurred!
